name: Build QA

on:
  push:
    branches:
      - qa

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Build binaries
        run: |
          poetry run pyinstaller --icon=assets/logo-rewsty.ico --onefile rewst_remote_agent.py
          poetry run pyinstaller --icon=assets/logo-rewsty.ico --onefile rewst_service_manager.py
          poetry run pyinstaller --icon=assets/logo-rewsty.ico --onefile rewst_agent_config.py
          poetry run pyinstaller --icon=assets/logo-rewsty.ico --onefile rewst_windows_service.py
      
      - name: Generate checksums
        run: |
          Get-FileHash -P ath ./dist/rewst_remote_agent.exe -Algorithm SHA256 | Format-List | Out-File -FilePath ./dist/rewst_remote_agent.exe.sha256
          Get-FileHash -Path ./dist/rewst_service_manager.exe -Algorithm SHA256 | Format-List | Out-File -FilePath ./dist/rewst_service_manager.exe.sha256
          Get-FileHash -Path ./dist/rewst_agent_config.exe -Algorithm SHA256 | Format-List | Out-File -FilePath ./dist/rewst_agent_config.exe.sha256
          Get-FileHash -Path ./dist/rewst_windows_service.exe -Algorithm SHA256 | Format-List | Out-File -FilePath ./dist/rewst_windows_service.exe.sha256

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: windows-latest-assets
          path: |
            ./dist/rewst_windows_service.exe
            ./dist/rewst_service_manager.exe
            ./dist/rewst_remote_agent.exe
            ./dist/rewst_agent_config.exe
            ./dist/rewst_windows_service.exe.sha256
            ./dist/rewst_service_manager.exe.sha256
            ./dist/rewst_remote_agent.exe.sha256
            ./dist/rewst_agent_config.exe.sha256
