name: Bump Version

on:
  push:
    branches: main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Save current version
        run: echo "VERSION=$(poetry version --short)" >> $GITHUB_ENV

      - name: Create branch for bump
        run: |
            git checkout -b "bump/v$VERSION"
            git push --set-upstream origin "bump/v$VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version and push
        run: |
            poetry run cz bump --yes
            git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request and approve
        run: |
            gh pr create -B main -H "bump/v$VERSION" --title "Merge bump/v$VERSION into main" --body 'Created by Github action'
            gh pr merge --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}