name: Code Coverage

on:
  pull_request:
    branches: main

jobs:
  code-coverage:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run tests using coverage.py module
        run: poetry run pytest --cov=.

      - name: Generate lcov file
        run: poetry run coverage-lcov

      - name: Code coverage summary report
        uses: VGVentures/very-good-coverage@v1.1.1
        with:
          path: lcov.info
          min_coverage: 90
